PROVIDER_NAME_ANTHROPIC = 'Anthropic'
PROVIDER_NAME_OPENAI = 'OpenAI'
PROVIDER_NAME_XAI = 'XAI'
PROVIDER_NAME_GOOGLE = 'Google'

FUNCTIONALITY_CHAT = 'CHAT'
FUNCTIONALITY_IMAGE_UNDERSTANDING = 'IMAGE-UNDERSTANDING'
FUNCTIONALITY_REASONING = 'REASONING'

SUPPORTED_PROVIDERS = [PROVIDER_NAME_ANTHROPIC, PROVIDER_NAME_GOOGLE, PROVIDER_NAME_OPENAI, PROVIDER_NAME_XAI]
SUPPORTED_FUNCTIONALITY = [FUNCTIONALITY_CHAT, FUNCTIONALITY_IMAGE_UNDERSTANDING, FUNCTIONALITY_REASONING]
FUNCTIONALITY_TO_PROMPT_SYMBOL_MAP = {
    FUNCTIONALITY_CHAT: '?',
    FUNCTIONALITY_IMAGE_UNDERSTANDING: '#',
    FUNCTIONALITY_REASONING: '$'
}
